workflow: WES
input: /home/marc/wes_gatk/dev/empty_samples
output: /home/marc/wes_gatk/test_names
threads: 32
reference_fasta: /mnt/home/mansourt/annDB/broad_hg38/Homo_sapiens_assembly38.fasta
bed_file: /mnt/gs21/scratch/mansourt/wes_gatk/exome_bed/S07604715_Padded.bed
gff_file: /mnt/home/mansourt/annDB/broad_hg38/Homo_sapiens.GRCh38.109.gff3.gz
nirvana_path: /mnt/home/mansourt/annDB/Nirvana
annovar_path: /mnt/home/mansourt/annDB/annovar_source/annovar
generate_confs_only: true
dont_use_gatk_bestparctice: false
trimmomatic: false
trim_t: 4
trim_min_length: 30
slidingwindow_size: 4
slidingwindow_quality: 10
trimmomatic_extra_args: ''
skip_QC: false
threads_index: 4
threads_align: 4
aligner_extra_args: ''
reference_index: null
reference_output_path: null
reference_output_prefix: null
index_fasta: false
known_variants: /mnt/home/mansourt/annDB/broad_hg38/1000G_omni2.5.hg38.vcf.gz
caller_extra_args: ''
threads_calling: 4
dry_run: false
export_dag: false
smk_extra_args: ''
parse_snakemake_output: false
annovar_protocol: refGene,avsnp150,clinvar_20221231,cosmic70,dbnsfp31a_interpro,EAS.sites.2015_08,EUR.sites.2015_08,gme,gnomad211_exome,SAS.sites.2015_08
annovar_operation: g,f,f,f,f,f,f,f,f,f
continue: false
overwrite: false
name: guap_run
verbose: false
print_last_run: false
decompress: false
path: /home/marc/wes_gatk/dev/empty_samples
working_dir: /home/marc/wes_gatk/test_names
ext: fq.gz
tail: ''
R: ''
naming_pattern: Novagen
R_pattern: ''
compressed: true
total_mem: 135
GUAP_DIR: /home/marc/wes_gatk/
common_rules: /home/marc/wes_gatk//workflows/common/rules/
